package cn.vstore.core.model.vo;

import java.io.Serializable;

public class Account implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.login_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private String loginId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.passwd
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private String passwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.nickname
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.prosumer_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private Long prosumerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column account.cp_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private Long cpId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table account
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.login_id
     *
     * @return the value of account.login_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.login_id
     *
     * @param loginId the value for account.login_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.passwd
     *
     * @return the value of account.passwd
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.passwd
     *
     * @param passwd the value for account.passwd
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.nickname
     *
     * @return the value of account.nickname
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.nickname
     *
     * @param nickname the value for account.nickname
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.prosumer_id
     *
     * @return the value of account.prosumer_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public Long getProsumerId() {
        return prosumerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.prosumer_id
     *
     * @param prosumerId the value for account.prosumer_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setProsumerId(Long prosumerId) {
        this.prosumerId = prosumerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column account.cp_id
     *
     * @return the value of account.cp_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public Long getCpId() {
        return cpId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column account.cp_id
     *
     * @param cpId the value for account.cp_id
     *
     * @ibatorgenerated Tue Dec 13 18:13:54 CST 2011
     */
    public void setCpId(Long cpId) {
        this.cpId = cpId;
    }
}