package cn.vstore.core.model.vo;

import java.io.Serializable;

public class OrderPayInfoLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_pay_info_log.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_pay_info_log.order_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private Long orderId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_pay_info_log.payee_info
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private String payeeInfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table order_pay_info_log
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_pay_info_log.id
     *
     * @return the value of order_pay_info_log.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_pay_info_log.id
     *
     * @param id the value for order_pay_info_log.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_pay_info_log.order_id
     *
     * @return the value of order_pay_info_log.order_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_pay_info_log.order_id
     *
     * @param orderId the value for order_pay_info_log.order_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_pay_info_log.payee_info
     *
     * @return the value of order_pay_info_log.payee_info
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public String getPayeeInfo() {
        return payeeInfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_pay_info_log.payee_info
     *
     * @param payeeInfo the value for order_pay_info_log.payee_info
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setPayeeInfo(String payeeInfo) {
        this.payeeInfo = payeeInfo == null ? null : payeeInfo.trim();
    }
}