package cn.vstore.core.model.vo;

import java.io.Serializable;

public class StorePayeeInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column store_payee_info.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column store_payee_info.store_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private Long storeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column store_payee_info.pay_type
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private Integer payType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column store_payee_info.key1
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private String key1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column store_payee_info.key2
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private String key2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table store_payee_info
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column store_payee_info.id
     *
     * @return the value of store_payee_info.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column store_payee_info.id
     *
     * @param id the value for store_payee_info.id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column store_payee_info.store_id
     *
     * @return the value of store_payee_info.store_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column store_payee_info.store_id
     *
     * @param storeId the value for store_payee_info.store_id
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column store_payee_info.pay_type
     *
     * @return the value of store_payee_info.pay_type
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column store_payee_info.pay_type
     *
     * @param payType the value for store_payee_info.pay_type
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column store_payee_info.key1
     *
     * @return the value of store_payee_info.key1
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column store_payee_info.key1
     *
     * @param key1 the value for store_payee_info.key1
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column store_payee_info.key2
     *
     * @return the value of store_payee_info.key2
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public String getKey2() {
        return key2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column store_payee_info.key2
     *
     * @param key2 the value for store_payee_info.key2
     *
     * @ibatorgenerated Fri Dec 16 14:09:54 CST 2011
     */
    public void setKey2(String key2) {
        this.key2 = key2 == null ? null : key2.trim();
    }
}