package cn.vstore.appserver.api.payment;

class PaymentKey {
	
	static final String G_PAYMENT_PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUXxtN4khfOVuaCJiCB02PoFj1UCWeH5iARypSfKAthR8ifYP19hwzwBxxN6dQmEnsNd8rxdLUKbu4G3yHP5GTrGt1xniP4OIFeYP2TuUBclv6DS+5 ycaccOiyZBvLyp6PS3pOmYYovez/RoMclSZ49RiJqckgm0vUpn+oJ0mlPQIDAQAB";


}
