package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class IpayUserGamePayLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.IPAY_USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String ipayUserId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.PROPS_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String propsId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.PROPS_TYPE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer propsTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.PAYMENT_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer paymentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.PAY_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date payTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.AMOUNT
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Double amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.IPAY_TOKEN
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String ipayToken;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String iccid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.STATUS
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.MY_PRICE_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String myPriceType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.RET_CODE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String retCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.RIGHT_START_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date rightStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.RIGHT_END_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date rightEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.LAST_VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer lastVersionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.SERVICE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String serviceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.CANCEL_SRC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer cancelSrcType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String userUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.DOWNLOAD_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Long downloadId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.CANCEL_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date cancelTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.PAYMENT_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String paymentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.RET_CODE_API_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String retCodeApiName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Long storeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.SUBSTORE_OID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String substoreOid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ipay_user_gamepay_log.RET_MSG
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String retMsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ipay_user_gamepay_log
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.ID
     *
     * @return the value of ipay_user_gamepay_log.ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.ID
     *
     * @param id the value for ipay_user_gamepay_log.ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.IPAY_USER_ID
     *
     * @return the value of ipay_user_gamepay_log.IPAY_USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getIpayUserId() {
        return ipayUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.IPAY_USER_ID
     *
     * @param ipayUserId the value for ipay_user_gamepay_log.IPAY_USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setIpayUserId(String ipayUserId) {
        this.ipayUserId = ipayUserId == null ? null : ipayUserId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.USER_ID
     *
     * @return the value of ipay_user_gamepay_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.USER_ID
     *
     * @param userId the value for ipay_user_gamepay_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.PROPS_ID
     *
     * @return the value of ipay_user_gamepay_log.PROPS_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getPropsId() {
        return propsId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.PROPS_ID
     *
     * @param propsId the value for ipay_user_gamepay_log.PROPS_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setPropsId(String propsId) {
        this.propsId = propsId == null ? null : propsId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.PROPS_TYPE_ID
     *
     * @return the value of ipay_user_gamepay_log.PROPS_TYPE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getPropsTypeId() {
        return propsTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.PROPS_TYPE_ID
     *
     * @param versionId the value for ipay_user_gamepay_log.PROPS_TYPE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setPropsTypeId(Integer propsTypeId) {
        this.propsTypeId = propsTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.PAYMENT_TYPE
     *
     * @return the value of ipay_user_gamepay_log.PAYMENT_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.PAYMENT_TYPE
     *
     * @param paymentType the value for ipay_user_gamepay_log.PAYMENT_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.PAY_TIME
     *
     * @return the value of ipay_user_gamepay_log.PAY_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.PAY_TIME
     *
     * @param payTime the value for ipay_user_gamepay_log.PAY_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.AMOUNT
     *
     * @return the value of ipay_user_gamepay_log.AMOUNT
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.AMOUNT
     *
     * @param amount the value for ipay_user_gamepay_log.AMOUNT
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.IPAY_TOKEN
     *
     * @return the value of ipay_user_gamepay_log.IPAY_TOKEN
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getIpayToken() {
        return ipayToken;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.IPAY_TOKEN
     *
     * @param ipayToken the value for ipay_user_gamepay_log.IPAY_TOKEN
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setIpayToken(String ipayToken) {
        this.ipayToken = ipayToken == null ? null : ipayToken.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.ICCID
     *
     * @return the value of ipay_user_gamepay_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.ICCID
     *
     * @param iccid the value for ipay_user_gamepay_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.IMEI
     *
     * @return the value of ipay_user_gamepay_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.IMEI
     *
     * @param imei the value for ipay_user_gamepay_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.STATUS
     *
     * @return the value of ipay_user_gamepay_log.STATUS
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.STATUS
     *
     * @param status the value for ipay_user_gamepay_log.STATUS
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.MY_PRICE_TYPE
     *
     * @return the value of ipay_user_gamepay_log.MY_PRICE_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getMyPriceType() {
        return myPriceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.MY_PRICE_TYPE
     *
     * @param myPriceType the value for ipay_user_gamepay_log.MY_PRICE_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setMyPriceType(String myPriceType) {
        this.myPriceType = myPriceType == null ? null : myPriceType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.RET_CODE
     *
     * @return the value of ipay_user_gamepay_log.RET_CODE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getRetCode() {
        return retCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.RET_CODE
     *
     * @param retCode the value for ipay_user_gamepay_log.RET_CODE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setRetCode(String retCode) {
        this.retCode = retCode == null ? null : retCode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.RIGHT_START_DATE
     *
     * @return the value of ipay_user_gamepay_log.RIGHT_START_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getRightStartDate() {
        return rightStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.RIGHT_START_DATE
     *
     * @param rightStartDate the value for ipay_user_gamepay_log.RIGHT_START_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setRightStartDate(Date rightStartDate) {
        this.rightStartDate = rightStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.RIGHT_END_DATE
     *
     * @return the value of ipay_user_gamepay_log.RIGHT_END_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getRightEndDate() {
        return rightEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.RIGHT_END_DATE
     *
     * @param rightEndDate the value for ipay_user_gamepay_log.RIGHT_END_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setRightEndDate(Date rightEndDate) {
        this.rightEndDate = rightEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.LAST_VERSION_ID
     *
     * @return the value of ipay_user_gamepay_log.LAST_VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getLastVersionId() {
        return lastVersionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.LAST_VERSION_ID
     *
     * @param lastVersionId the value for ipay_user_gamepay_log.LAST_VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setLastVersionId(Integer lastVersionId) {
        this.lastVersionId = lastVersionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.SERVICE_ID
     *
     * @return the value of ipay_user_gamepay_log.SERVICE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.SERVICE_ID
     *
     * @param serviceId the value for ipay_user_gamepay_log.SERVICE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.CANCEL_SRC_TYPE
     *
     * @return the value of ipay_user_gamepay_log.CANCEL_SRC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getCancelSrcType() {
        return cancelSrcType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.CANCEL_SRC_TYPE
     *
     * @param cancelSrcType the value for ipay_user_gamepay_log.CANCEL_SRC_TYPE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setCancelSrcType(Integer cancelSrcType) {
        this.cancelSrcType = cancelSrcType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.USER_UID
     *
     * @return the value of ipay_user_gamepay_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.USER_UID
     *
     * @param userUid the value for ipay_user_gamepay_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.DOWNLOAD_ID
     *
     * @return the value of ipay_user_gamepay_log.DOWNLOAD_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Long getDownloadId() {
        return downloadId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.DOWNLOAD_ID
     *
     * @param downloadId the value for ipay_user_gamepay_log.DOWNLOAD_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setDownloadId(Long downloadId) {
        this.downloadId = downloadId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.CANCEL_TIME
     *
     * @return the value of ipay_user_gamepay_log.CANCEL_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.CANCEL_TIME
     *
     * @param cancelTime the value for ipay_user_gamepay_log.CANCEL_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setCancelTime(Date cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.PAYMENT_ID
     *
     * @return the value of ipay_user_gamepay_log.PAYMENT_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.PAYMENT_ID
     *
     * @param paymentId the value for ipay_user_gamepay_log.PAYMENT_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId == null ? null : paymentId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.RET_CODE_API_NAME
     *
     * @return the value of ipay_user_gamepay_log.RET_CODE_API_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getRetCodeApiName() {
        return retCodeApiName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.RET_CODE_API_NAME
     *
     * @param retCodeApiName the value for ipay_user_gamepay_log.RET_CODE_API_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setRetCodeApiName(String retCodeApiName) {
        this.retCodeApiName = retCodeApiName == null ? null : retCodeApiName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.STORE_ID
     *
     * @return the value of ipay_user_gamepay_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.STORE_ID
     *
     * @param storeId the value for ipay_user_gamepay_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.SUBSTORE_OID
     *
     * @return the value of ipay_user_gamepay_log.SUBSTORE_OID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getSubstoreOid() {
        return substoreOid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.SUBSTORE_OID
     *
     * @param substoreOid the value for ipay_user_gamepay_log.SUBSTORE_OID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setSubstoreOid(String substoreOid) {
        this.substoreOid = substoreOid == null ? null : substoreOid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ipay_user_gamepay_log.RET_MSG
     *
     * @return the value of ipay_user_gamepay_log.RET_MSG
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getRetMsg() {
        return retMsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ipay_user_gamepay_log.RET_MSG
     *
     * @param retMsg the value for ipay_user_gamepay_log.RET_MSG
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setRetMsg(String retMsg) {
        this.retMsg = retMsg == null ? null : retMsg.trim();
    }
}