package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class StoreClientBehaviorLog implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.LOG_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private Long logUid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.VERSION_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private Integer versionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.USER_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.ICCID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String iccid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.LOG_DATE
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private Date logDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.IMEI
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String imei;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.APP_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String appId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.OPEN_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private Date openTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.MSISDN
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String msisdn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.MODEL_NAME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String modelName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.USER_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String userUid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.IS_FIRST_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private Double isFirstTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.SNUM
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String snum;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column store_client_behavior_log.IP
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private String ip;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.LOG_UID
	 * @return  the value of store_client_behavior_log.LOG_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Long getLogUid() {
		return logUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.LOG_UID
	 * @param logUid  the value for store_client_behavior_log.LOG_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setLogUid(Long logUid) {
		this.logUid = logUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.VERSION_ID
	 * @return  the value of store_client_behavior_log.VERSION_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Integer getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.VERSION_ID
	 * @param versionId  the value for store_client_behavior_log.VERSION_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setVersionId(Integer versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.USER_ID
	 * @return  the value of store_client_behavior_log.USER_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.USER_ID
	 * @param userId  the value for store_client_behavior_log.USER_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.ICCID
	 * @return  the value of store_client_behavior_log.ICCID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getIccid() {
		return iccid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.ICCID
	 * @param iccid  the value for store_client_behavior_log.ICCID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setIccid(String iccid) {
		this.iccid = iccid == null ? null : iccid.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.LOG_DATE
	 * @return  the value of store_client_behavior_log.LOG_DATE
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Date getLogDate() {
		return logDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.LOG_DATE
	 * @param logDate  the value for store_client_behavior_log.LOG_DATE
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.IMEI
	 * @return  the value of store_client_behavior_log.IMEI
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.IMEI
	 * @param imei  the value for store_client_behavior_log.IMEI
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setImei(String imei) {
		this.imei = imei == null ? null : imei.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.APP_ID
	 * @return  the value of store_client_behavior_log.APP_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.APP_ID
	 * @param appId  the value for store_client_behavior_log.APP_ID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setAppId(String appId) {
		this.appId = appId == null ? null : appId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.OPEN_TIME
	 * @return  the value of store_client_behavior_log.OPEN_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Date getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.OPEN_TIME
	 * @param openTime  the value for store_client_behavior_log.OPEN_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.MSISDN
	 * @return  the value of store_client_behavior_log.MSISDN
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getMsisdn() {
		return msisdn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.MSISDN
	 * @param msisdn  the value for store_client_behavior_log.MSISDN
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn == null ? null : msisdn.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.MODEL_NAME
	 * @return  the value of store_client_behavior_log.MODEL_NAME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getModelName() {
		return modelName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.MODEL_NAME
	 * @param modelName  the value for store_client_behavior_log.MODEL_NAME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setModelName(String modelName) {
		this.modelName = modelName == null ? null : modelName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.USER_UID
	 * @return  the value of store_client_behavior_log.USER_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getUserUid() {
		return userUid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.USER_UID
	 * @param userUid  the value for store_client_behavior_log.USER_UID
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setUserUid(String userUid) {
		this.userUid = userUid == null ? null : userUid.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.IS_FIRST_TIME
	 * @return  the value of store_client_behavior_log.IS_FIRST_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Double getIsFirstTime() {
		return isFirstTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.IS_FIRST_TIME
	 * @param isFirstTime  the value for store_client_behavior_log.IS_FIRST_TIME
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setIsFirstTime(Double isFirstTime) {
		this.isFirstTime = isFirstTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.SNUM
	 * @return  the value of store_client_behavior_log.SNUM
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getSnum() {
		return snum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.SNUM
	 * @param snum  the value for store_client_behavior_log.SNUM
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setSnum(String snum) {
		this.snum = snum == null ? null : snum.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column store_client_behavior_log.IP
	 * @return  the value of store_client_behavior_log.IP
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column store_client_behavior_log.IP
	 * @param ip  the value for store_client_behavior_log.IP
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}
}