package cn.vstore.appserver.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StoreClientBehaviorLogExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public StoreClientBehaviorLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	protected StoreClientBehaviorLogExample(
			StoreClientBehaviorLogExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table store_client_behavior_log
	 * @ibatorgenerated  Wed Mar 28 17:19:37 CST 2012
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andLogUidIsNull() {
			addCriterion("LOG_UID is null");
			return this;
		}

		public Criteria andLogUidIsNotNull() {
			addCriterion("LOG_UID is not null");
			return this;
		}

		public Criteria andLogUidEqualTo(Long value) {
			addCriterion("LOG_UID =", value, "logUid");
			return this;
		}

		public Criteria andLogUidNotEqualTo(Long value) {
			addCriterion("LOG_UID <>", value, "logUid");
			return this;
		}

		public Criteria andLogUidGreaterThan(Long value) {
			addCriterion("LOG_UID >", value, "logUid");
			return this;
		}

		public Criteria andLogUidGreaterThanOrEqualTo(Long value) {
			addCriterion("LOG_UID >=", value, "logUid");
			return this;
		}

		public Criteria andLogUidLessThan(Long value) {
			addCriterion("LOG_UID <", value, "logUid");
			return this;
		}

		public Criteria andLogUidLessThanOrEqualTo(Long value) {
			addCriterion("LOG_UID <=", value, "logUid");
			return this;
		}

		public Criteria andLogUidIn(List<Long> values) {
			addCriterion("LOG_UID in", values, "logUid");
			return this;
		}

		public Criteria andLogUidNotIn(List<Long> values) {
			addCriterion("LOG_UID not in", values, "logUid");
			return this;
		}

		public Criteria andLogUidBetween(Long value1, Long value2) {
			addCriterion("LOG_UID between", value1, value2, "logUid");
			return this;
		}

		public Criteria andLogUidNotBetween(Long value1, Long value2) {
			addCriterion("LOG_UID not between", value1, value2, "logUid");
			return this;
		}

		public Criteria andVersionIdIsNull() {
			addCriterion("VERSION_ID is null");
			return this;
		}

		public Criteria andVersionIdIsNotNull() {
			addCriterion("VERSION_ID is not null");
			return this;
		}

		public Criteria andVersionIdEqualTo(Integer value) {
			addCriterion("VERSION_ID =", value, "versionId");
			return this;
		}

		public Criteria andVersionIdNotEqualTo(Integer value) {
			addCriterion("VERSION_ID <>", value, "versionId");
			return this;
		}

		public Criteria andVersionIdGreaterThan(Integer value) {
			addCriterion("VERSION_ID >", value, "versionId");
			return this;
		}

		public Criteria andVersionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("VERSION_ID >=", value, "versionId");
			return this;
		}

		public Criteria andVersionIdLessThan(Integer value) {
			addCriterion("VERSION_ID <", value, "versionId");
			return this;
		}

		public Criteria andVersionIdLessThanOrEqualTo(Integer value) {
			addCriterion("VERSION_ID <=", value, "versionId");
			return this;
		}

		public Criteria andVersionIdIn(List<Integer> values) {
			addCriterion("VERSION_ID in", values, "versionId");
			return this;
		}

		public Criteria andVersionIdNotIn(List<Integer> values) {
			addCriterion("VERSION_ID not in", values, "versionId");
			return this;
		}

		public Criteria andVersionIdBetween(Integer value1, Integer value2) {
			addCriterion("VERSION_ID between", value1, value2, "versionId");
			return this;
		}

		public Criteria andVersionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("VERSION_ID not between", value1, value2, "versionId");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return this;
		}

		public Criteria andIccidIsNull() {
			addCriterion("ICCID is null");
			return this;
		}

		public Criteria andIccidIsNotNull() {
			addCriterion("ICCID is not null");
			return this;
		}

		public Criteria andIccidEqualTo(String value) {
			addCriterion("ICCID =", value, "iccid");
			return this;
		}

		public Criteria andIccidNotEqualTo(String value) {
			addCriterion("ICCID <>", value, "iccid");
			return this;
		}

		public Criteria andIccidGreaterThan(String value) {
			addCriterion("ICCID >", value, "iccid");
			return this;
		}

		public Criteria andIccidGreaterThanOrEqualTo(String value) {
			addCriterion("ICCID >=", value, "iccid");
			return this;
		}

		public Criteria andIccidLessThan(String value) {
			addCriterion("ICCID <", value, "iccid");
			return this;
		}

		public Criteria andIccidLessThanOrEqualTo(String value) {
			addCriterion("ICCID <=", value, "iccid");
			return this;
		}

		public Criteria andIccidLike(String value) {
			addCriterion("ICCID like", value, "iccid");
			return this;
		}

		public Criteria andIccidNotLike(String value) {
			addCriterion("ICCID not like", value, "iccid");
			return this;
		}

		public Criteria andIccidIn(List<String> values) {
			addCriterion("ICCID in", values, "iccid");
			return this;
		}

		public Criteria andIccidNotIn(List<String> values) {
			addCriterion("ICCID not in", values, "iccid");
			return this;
		}

		public Criteria andIccidBetween(String value1, String value2) {
			addCriterion("ICCID between", value1, value2, "iccid");
			return this;
		}

		public Criteria andIccidNotBetween(String value1, String value2) {
			addCriterion("ICCID not between", value1, value2, "iccid");
			return this;
		}

		public Criteria andLogDateIsNull() {
			addCriterion("LOG_DATE is null");
			return this;
		}

		public Criteria andLogDateIsNotNull() {
			addCriterion("LOG_DATE is not null");
			return this;
		}

		public Criteria andLogDateEqualTo(Date value) {
			addCriterion("LOG_DATE =", value, "logDate");
			return this;
		}

		public Criteria andLogDateNotEqualTo(Date value) {
			addCriterion("LOG_DATE <>", value, "logDate");
			return this;
		}

		public Criteria andLogDateGreaterThan(Date value) {
			addCriterion("LOG_DATE >", value, "logDate");
			return this;
		}

		public Criteria andLogDateGreaterThanOrEqualTo(Date value) {
			addCriterion("LOG_DATE >=", value, "logDate");
			return this;
		}

		public Criteria andLogDateLessThan(Date value) {
			addCriterion("LOG_DATE <", value, "logDate");
			return this;
		}

		public Criteria andLogDateLessThanOrEqualTo(Date value) {
			addCriterion("LOG_DATE <=", value, "logDate");
			return this;
		}

		public Criteria andLogDateIn(List<Date> values) {
			addCriterion("LOG_DATE in", values, "logDate");
			return this;
		}

		public Criteria andLogDateNotIn(List<Date> values) {
			addCriterion("LOG_DATE not in", values, "logDate");
			return this;
		}

		public Criteria andLogDateBetween(Date value1, Date value2) {
			addCriterion("LOG_DATE between", value1, value2, "logDate");
			return this;
		}

		public Criteria andLogDateNotBetween(Date value1, Date value2) {
			addCriterion("LOG_DATE not between", value1, value2, "logDate");
			return this;
		}

		public Criteria andImeiIsNull() {
			addCriterion("IMEI is null");
			return this;
		}

		public Criteria andImeiIsNotNull() {
			addCriterion("IMEI is not null");
			return this;
		}

		public Criteria andImeiEqualTo(String value) {
			addCriterion("IMEI =", value, "imei");
			return this;
		}

		public Criteria andImeiNotEqualTo(String value) {
			addCriterion("IMEI <>", value, "imei");
			return this;
		}

		public Criteria andImeiGreaterThan(String value) {
			addCriterion("IMEI >", value, "imei");
			return this;
		}

		public Criteria andImeiGreaterThanOrEqualTo(String value) {
			addCriterion("IMEI >=", value, "imei");
			return this;
		}

		public Criteria andImeiLessThan(String value) {
			addCriterion("IMEI <", value, "imei");
			return this;
		}

		public Criteria andImeiLessThanOrEqualTo(String value) {
			addCriterion("IMEI <=", value, "imei");
			return this;
		}

		public Criteria andImeiLike(String value) {
			addCriterion("IMEI like", value, "imei");
			return this;
		}

		public Criteria andImeiNotLike(String value) {
			addCriterion("IMEI not like", value, "imei");
			return this;
		}

		public Criteria andImeiIn(List<String> values) {
			addCriterion("IMEI in", values, "imei");
			return this;
		}

		public Criteria andImeiNotIn(List<String> values) {
			addCriterion("IMEI not in", values, "imei");
			return this;
		}

		public Criteria andImeiBetween(String value1, String value2) {
			addCriterion("IMEI between", value1, value2, "imei");
			return this;
		}

		public Criteria andImeiNotBetween(String value1, String value2) {
			addCriterion("IMEI not between", value1, value2, "imei");
			return this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("APP_ID is null");
			return this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("APP_ID is not null");
			return this;
		}

		public Criteria andAppIdEqualTo(String value) {
			addCriterion("APP_ID =", value, "appId");
			return this;
		}

		public Criteria andAppIdNotEqualTo(String value) {
			addCriterion("APP_ID <>", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThan(String value) {
			addCriterion("APP_ID >", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(String value) {
			addCriterion("APP_ID >=", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThan(String value) {
			addCriterion("APP_ID <", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThanOrEqualTo(String value) {
			addCriterion("APP_ID <=", value, "appId");
			return this;
		}

		public Criteria andAppIdLike(String value) {
			addCriterion("APP_ID like", value, "appId");
			return this;
		}

		public Criteria andAppIdNotLike(String value) {
			addCriterion("APP_ID not like", value, "appId");
			return this;
		}

		public Criteria andAppIdIn(List<String> values) {
			addCriterion("APP_ID in", values, "appId");
			return this;
		}

		public Criteria andAppIdNotIn(List<String> values) {
			addCriterion("APP_ID not in", values, "appId");
			return this;
		}

		public Criteria andAppIdBetween(String value1, String value2) {
			addCriterion("APP_ID between", value1, value2, "appId");
			return this;
		}

		public Criteria andAppIdNotBetween(String value1, String value2) {
			addCriterion("APP_ID not between", value1, value2, "appId");
			return this;
		}

		public Criteria andOpenTimeIsNull() {
			addCriterion("OPEN_TIME is null");
			return this;
		}

		public Criteria andOpenTimeIsNotNull() {
			addCriterion("OPEN_TIME is not null");
			return this;
		}

		public Criteria andOpenTimeEqualTo(Date value) {
			addCriterion("OPEN_TIME =", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeNotEqualTo(Date value) {
			addCriterion("OPEN_TIME <>", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeGreaterThan(Date value) {
			addCriterion("OPEN_TIME >", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("OPEN_TIME >=", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeLessThan(Date value) {
			addCriterion("OPEN_TIME <", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeLessThanOrEqualTo(Date value) {
			addCriterion("OPEN_TIME <=", value, "openTime");
			return this;
		}

		public Criteria andOpenTimeIn(List<Date> values) {
			addCriterion("OPEN_TIME in", values, "openTime");
			return this;
		}

		public Criteria andOpenTimeNotIn(List<Date> values) {
			addCriterion("OPEN_TIME not in", values, "openTime");
			return this;
		}

		public Criteria andOpenTimeBetween(Date value1, Date value2) {
			addCriterion("OPEN_TIME between", value1, value2, "openTime");
			return this;
		}

		public Criteria andOpenTimeNotBetween(Date value1, Date value2) {
			addCriterion("OPEN_TIME not between", value1, value2, "openTime");
			return this;
		}

		public Criteria andMsisdnIsNull() {
			addCriterion("MSISDN is null");
			return this;
		}

		public Criteria andMsisdnIsNotNull() {
			addCriterion("MSISDN is not null");
			return this;
		}

		public Criteria andMsisdnEqualTo(String value) {
			addCriterion("MSISDN =", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnNotEqualTo(String value) {
			addCriterion("MSISDN <>", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnGreaterThan(String value) {
			addCriterion("MSISDN >", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnGreaterThanOrEqualTo(String value) {
			addCriterion("MSISDN >=", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnLessThan(String value) {
			addCriterion("MSISDN <", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnLessThanOrEqualTo(String value) {
			addCriterion("MSISDN <=", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnLike(String value) {
			addCriterion("MSISDN like", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnNotLike(String value) {
			addCriterion("MSISDN not like", value, "msisdn");
			return this;
		}

		public Criteria andMsisdnIn(List<String> values) {
			addCriterion("MSISDN in", values, "msisdn");
			return this;
		}

		public Criteria andMsisdnNotIn(List<String> values) {
			addCriterion("MSISDN not in", values, "msisdn");
			return this;
		}

		public Criteria andMsisdnBetween(String value1, String value2) {
			addCriterion("MSISDN between", value1, value2, "msisdn");
			return this;
		}

		public Criteria andMsisdnNotBetween(String value1, String value2) {
			addCriterion("MSISDN not between", value1, value2, "msisdn");
			return this;
		}

		public Criteria andModelNameIsNull() {
			addCriterion("MODEL_NAME is null");
			return this;
		}

		public Criteria andModelNameIsNotNull() {
			addCriterion("MODEL_NAME is not null");
			return this;
		}

		public Criteria andModelNameEqualTo(String value) {
			addCriterion("MODEL_NAME =", value, "modelName");
			return this;
		}

		public Criteria andModelNameNotEqualTo(String value) {
			addCriterion("MODEL_NAME <>", value, "modelName");
			return this;
		}

		public Criteria andModelNameGreaterThan(String value) {
			addCriterion("MODEL_NAME >", value, "modelName");
			return this;
		}

		public Criteria andModelNameGreaterThanOrEqualTo(String value) {
			addCriterion("MODEL_NAME >=", value, "modelName");
			return this;
		}

		public Criteria andModelNameLessThan(String value) {
			addCriterion("MODEL_NAME <", value, "modelName");
			return this;
		}

		public Criteria andModelNameLessThanOrEqualTo(String value) {
			addCriterion("MODEL_NAME <=", value, "modelName");
			return this;
		}

		public Criteria andModelNameLike(String value) {
			addCriterion("MODEL_NAME like", value, "modelName");
			return this;
		}

		public Criteria andModelNameNotLike(String value) {
			addCriterion("MODEL_NAME not like", value, "modelName");
			return this;
		}

		public Criteria andModelNameIn(List<String> values) {
			addCriterion("MODEL_NAME in", values, "modelName");
			return this;
		}

		public Criteria andModelNameNotIn(List<String> values) {
			addCriterion("MODEL_NAME not in", values, "modelName");
			return this;
		}

		public Criteria andModelNameBetween(String value1, String value2) {
			addCriterion("MODEL_NAME between", value1, value2, "modelName");
			return this;
		}

		public Criteria andModelNameNotBetween(String value1, String value2) {
			addCriterion("MODEL_NAME not between", value1, value2, "modelName");
			return this;
		}

		public Criteria andUserUidIsNull() {
			addCriterion("USER_UID is null");
			return this;
		}

		public Criteria andUserUidIsNotNull() {
			addCriterion("USER_UID is not null");
			return this;
		}

		public Criteria andUserUidEqualTo(String value) {
			addCriterion("USER_UID =", value, "userUid");
			return this;
		}

		public Criteria andUserUidNotEqualTo(String value) {
			addCriterion("USER_UID <>", value, "userUid");
			return this;
		}

		public Criteria andUserUidGreaterThan(String value) {
			addCriterion("USER_UID >", value, "userUid");
			return this;
		}

		public Criteria andUserUidGreaterThanOrEqualTo(String value) {
			addCriterion("USER_UID >=", value, "userUid");
			return this;
		}

		public Criteria andUserUidLessThan(String value) {
			addCriterion("USER_UID <", value, "userUid");
			return this;
		}

		public Criteria andUserUidLessThanOrEqualTo(String value) {
			addCriterion("USER_UID <=", value, "userUid");
			return this;
		}

		public Criteria andUserUidLike(String value) {
			addCriterion("USER_UID like", value, "userUid");
			return this;
		}

		public Criteria andUserUidNotLike(String value) {
			addCriterion("USER_UID not like", value, "userUid");
			return this;
		}

		public Criteria andUserUidIn(List<String> values) {
			addCriterion("USER_UID in", values, "userUid");
			return this;
		}

		public Criteria andUserUidNotIn(List<String> values) {
			addCriterion("USER_UID not in", values, "userUid");
			return this;
		}

		public Criteria andUserUidBetween(String value1, String value2) {
			addCriterion("USER_UID between", value1, value2, "userUid");
			return this;
		}

		public Criteria andUserUidNotBetween(String value1, String value2) {
			addCriterion("USER_UID not between", value1, value2, "userUid");
			return this;
		}

		public Criteria andIsFirstTimeIsNull() {
			addCriterion("IS_FIRST_TIME is null");
			return this;
		}

		public Criteria andIsFirstTimeIsNotNull() {
			addCriterion("IS_FIRST_TIME is not null");
			return this;
		}

		public Criteria andIsFirstTimeEqualTo(Double value) {
			addCriterion("IS_FIRST_TIME =", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeNotEqualTo(Double value) {
			addCriterion("IS_FIRST_TIME <>", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeGreaterThan(Double value) {
			addCriterion("IS_FIRST_TIME >", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeGreaterThanOrEqualTo(Double value) {
			addCriterion("IS_FIRST_TIME >=", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeLessThan(Double value) {
			addCriterion("IS_FIRST_TIME <", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeLessThanOrEqualTo(Double value) {
			addCriterion("IS_FIRST_TIME <=", value, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeIn(List<Double> values) {
			addCriterion("IS_FIRST_TIME in", values, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeNotIn(List<Double> values) {
			addCriterion("IS_FIRST_TIME not in", values, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeBetween(Double value1, Double value2) {
			addCriterion("IS_FIRST_TIME between", value1, value2, "isFirstTime");
			return this;
		}

		public Criteria andIsFirstTimeNotBetween(Double value1, Double value2) {
			addCriterion("IS_FIRST_TIME not between", value1, value2,
					"isFirstTime");
			return this;
		}

		public Criteria andSnumIsNull() {
			addCriterion("SNUM is null");
			return this;
		}

		public Criteria andSnumIsNotNull() {
			addCriterion("SNUM is not null");
			return this;
		}

		public Criteria andSnumEqualTo(String value) {
			addCriterion("SNUM =", value, "snum");
			return this;
		}

		public Criteria andSnumNotEqualTo(String value) {
			addCriterion("SNUM <>", value, "snum");
			return this;
		}

		public Criteria andSnumGreaterThan(String value) {
			addCriterion("SNUM >", value, "snum");
			return this;
		}

		public Criteria andSnumGreaterThanOrEqualTo(String value) {
			addCriterion("SNUM >=", value, "snum");
			return this;
		}

		public Criteria andSnumLessThan(String value) {
			addCriterion("SNUM <", value, "snum");
			return this;
		}

		public Criteria andSnumLessThanOrEqualTo(String value) {
			addCriterion("SNUM <=", value, "snum");
			return this;
		}

		public Criteria andSnumLike(String value) {
			addCriterion("SNUM like", value, "snum");
			return this;
		}

		public Criteria andSnumNotLike(String value) {
			addCriterion("SNUM not like", value, "snum");
			return this;
		}

		public Criteria andSnumIn(List<String> values) {
			addCriterion("SNUM in", values, "snum");
			return this;
		}

		public Criteria andSnumNotIn(List<String> values) {
			addCriterion("SNUM not in", values, "snum");
			return this;
		}

		public Criteria andSnumBetween(String value1, String value2) {
			addCriterion("SNUM between", value1, value2, "snum");
			return this;
		}

		public Criteria andSnumNotBetween(String value1, String value2) {
			addCriterion("SNUM not between", value1, value2, "snum");
			return this;
		}

		public Criteria andIpIsNull() {
			addCriterion("IP is null");
			return this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("IP is not null");
			return this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("IP =", value, "ip");
			return this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("IP <>", value, "ip");
			return this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("IP >", value, "ip");
			return this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("IP >=", value, "ip");
			return this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("IP <", value, "ip");
			return this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("IP <=", value, "ip");
			return this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("IP like", value, "ip");
			return this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("IP not like", value, "ip");
			return this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("IP in", values, "ip");
			return this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("IP not in", values, "ip");
			return this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("IP between", value1, value2, "ip");
			return this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("IP not between", value1, value2, "ip");
			return this;
		}
	}
}