package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserBehaviorLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.LOG_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Long logUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String iccid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String imei;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.APP_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String appId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Integer versionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.OPEN_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date openTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.LOG_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Date logDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.MODEL_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String modelName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.IS_DELETE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Double isDelete;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private String userUid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_behavior_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private Long storeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table user_behavior_log
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.LOG_UID
     *
     * @return the value of user_behavior_log.LOG_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Long getLogUid() {
        return logUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.LOG_UID
     *
     * @param logUid the value for user_behavior_log.LOG_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setLogUid(Long logUid) {
        this.logUid = logUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.USER_ID
     *
     * @return the value of user_behavior_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.USER_ID
     *
     * @param userId the value for user_behavior_log.USER_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.ICCID
     *
     * @return the value of user_behavior_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.ICCID
     *
     * @param iccid the value for user_behavior_log.ICCID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.IMEI
     *
     * @return the value of user_behavior_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.IMEI
     *
     * @param imei the value for user_behavior_log.IMEI
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.APP_ID
     *
     * @return the value of user_behavior_log.APP_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.APP_ID
     *
     * @param appId the value for user_behavior_log.APP_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.VERSION_ID
     *
     * @return the value of user_behavior_log.VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.VERSION_ID
     *
     * @param versionId the value for user_behavior_log.VERSION_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.OPEN_TIME
     *
     * @return the value of user_behavior_log.OPEN_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.OPEN_TIME
     *
     * @param openTime the value for user_behavior_log.OPEN_TIME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.LOG_DATE
     *
     * @return the value of user_behavior_log.LOG_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.LOG_DATE
     *
     * @param logDate the value for user_behavior_log.LOG_DATE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.MODEL_NAME
     *
     * @return the value of user_behavior_log.MODEL_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.MODEL_NAME
     *
     * @param modelName the value for user_behavior_log.MODEL_NAME
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.IS_DELETE
     *
     * @return the value of user_behavior_log.IS_DELETE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Double getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.IS_DELETE
     *
     * @param isDelete the value for user_behavior_log.IS_DELETE
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setIsDelete(Double isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.USER_UID
     *
     * @return the value of user_behavior_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.USER_UID
     *
     * @param userUid the value for user_behavior_log.USER_UID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_behavior_log.STORE_ID
     *
     * @return the value of user_behavior_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_behavior_log.STORE_ID
     *
     * @param storeId the value for user_behavior_log.STORE_ID
     *
     * @ibatorgenerated Fri Jul 29 10:11:32 CST 2011
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }
}