package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserFeedSpace implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_space.id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_space.space_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    private Long spaceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_space.sp_time
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    private Date spTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_space.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    private Long paraId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_feed_space
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_space.id
     *
     * @return the value of v_user_feed_space.id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_space.id
     *
     * @param id the value for v_user_feed_space.id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_space.space_id
     *
     * @return the value of v_user_feed_space.space_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public Long getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_space.space_id
     *
     * @param spaceId the value for v_user_feed_space.space_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public void setSpaceId(Long spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_space.sp_time
     *
     * @return the value of v_user_feed_space.sp_time
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public Date getSpTime() {
        return spTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_space.sp_time
     *
     * @param spTime the value for v_user_feed_space.sp_time
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public void setSpTime(Date spTime) {
        this.spTime = spTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_space.para_id
     *
     * @return the value of v_user_feed_space.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_space.para_id
     *
     * @param paraId the value for v_user_feed_space.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:16:14 CST 2012
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }
}