package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserCollect implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_collect.id
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_collect.userid
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    private String userid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_collect.appid
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    private String appid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_collect.create_time
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_collect
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_collect.id
     *
     * @return the value of v_user_collect.id
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_collect.id
     *
     * @param id the value for v_user_collect.id
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_collect.userid
     *
     * @return the value of v_user_collect.userid
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
   

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_collect.appid
     *
     * @return the value of v_user_collect.appid
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_collect.appid
     *
     * @param appid the value for v_user_collect.appid
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_collect.create_time
     *
     * @return the value of v_user_collect.create_time
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_collect.create_time
     *
     * @param createTime the value for v_user_collect.create_time
     *
     * @ibatorgenerated Wed Aug 08 17:22:43 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
}