package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserFeedApp implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_app.id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_app.pkgName
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    private String pkgname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_app.pg_time
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    private Date pgTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_app.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    private Long paraId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_feed_app
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_app.id
     *
     * @return the value of v_user_feed_app.id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_app.id
     *
     * @param id the value for v_user_feed_app.id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_app.pkgName
     *
     * @return the value of v_user_feed_app.pkgName
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public String getPkgname() {
        return pkgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_app.pkgName
     *
     * @param pkgname the value for v_user_feed_app.pkgName
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname == null ? null : pkgname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_app.pg_time
     *
     * @return the value of v_user_feed_app.pg_time
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public Date getPgTime() {
        return pgTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_app.pg_time
     *
     * @param pgTime the value for v_user_feed_app.pg_time
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public void setPgTime(Date pgTime) {
        this.pgTime = pgTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_app.para_id
     *
     * @return the value of v_user_feed_app.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_app.para_id
     *
     * @param paraId the value for v_user_feed_app.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:04:36 CST 2012
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }
}