package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserFeedbackBehavior implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feedback_behavior.id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feedback_behavior.para_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private Long paraId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feedback_behavior.action_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private Long actionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feedback_behavior.times
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private Integer times;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feedback_behavior.b_time
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private Date bTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_feedback_behavior
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feedback_behavior.id
     *
     * @return the value of v_user_feedback_behavior.id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feedback_behavior.id
     *
     * @param id the value for v_user_feedback_behavior.id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feedback_behavior.para_id
     *
     * @return the value of v_user_feedback_behavior.para_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feedback_behavior.para_id
     *
     * @param paraId the value for v_user_feedback_behavior.para_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feedback_behavior.action_id
     *
     * @return the value of v_user_feedback_behavior.action_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public Long getActionId() {
        return actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feedback_behavior.action_id
     *
     * @param actionId the value for v_user_feedback_behavior.action_id
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feedback_behavior.times
     *
     * @return the value of v_user_feedback_behavior.times
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feedback_behavior.times
     *
     * @param times the value for v_user_feedback_behavior.times
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feedback_behavior.b_time
     *
     * @return the value of v_user_feedback_behavior.b_time
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public Date getbTime() {
        return bTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feedback_behavior.b_time
     *
     * @param bTime the value for v_user_feedback_behavior.b_time
     *
     * @ibatorgenerated Tue Jun 26 18:09:43 CST 2012
     */
    public void setbTime(Date bTime) {
        this.bTime = bTime;
    }
}