package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserFeedCategory implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_category.id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_category.category_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    private Long categoryId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_category.cat_time
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    private Date catTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_feed_category.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    private Long paraId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_feed_category
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_category.id
     *
     * @return the value of v_user_feed_category.id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_category.id
     *
     * @param id the value for v_user_feed_category.id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_category.category_id
     *
     * @return the value of v_user_feed_category.category_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_category.category_id
     *
     * @param categoryId the value for v_user_feed_category.category_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_category.cat_time
     *
     * @return the value of v_user_feed_category.cat_time
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public Date getCatTime() {
        return catTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_category.cat_time
     *
     * @param catTime the value for v_user_feed_category.cat_time
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public void setCatTime(Date catTime) {
        this.catTime = catTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_feed_category.para_id
     *
     * @return the value of v_user_feed_category.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_feed_category.para_id
     *
     * @param paraId the value for v_user_feed_category.para_id
     *
     * @ibatorgenerated Thu Jun 28 15:11:10 CST 2012
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }
}