package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class UserSearchwords implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.keywords
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private String keywords;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.descr
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private String descr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.remarks
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private String remarks;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.times
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private Integer times;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.s_time
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private Date sTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_user_searchwords.para_id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private Long paraId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_user_searchwords
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.id
     *
     * @return the value of v_user_searchwords.id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.id
     *
     * @param id the value for v_user_searchwords.id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.keywords
     *
     * @return the value of v_user_searchwords.keywords
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.keywords
     *
     * @param keywords the value for v_user_searchwords.keywords
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.descr
     *
     * @return the value of v_user_searchwords.descr
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.descr
     *
     * @param descr the value for v_user_searchwords.descr
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.remarks
     *
     * @return the value of v_user_searchwords.remarks
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.remarks
     *
     * @param remarks the value for v_user_searchwords.remarks
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.times
     *
     * @return the value of v_user_searchwords.times
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.times
     *
     * @param times the value for v_user_searchwords.times
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.s_time
     *
     * @return the value of v_user_searchwords.s_time
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public Date getsTime() {
        return sTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.s_time
     *
     * @param sTime the value for v_user_searchwords.s_time
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setsTime(Date sTime) {
        this.sTime = sTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_user_searchwords.para_id
     *
     * @return the value of v_user_searchwords.para_id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public Long getParaId() {
        return paraId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_user_searchwords.para_id
     *
     * @param paraId the value for v_user_searchwords.para_id
     *
     * @ibatorgenerated Tue Jun 26 21:26:53 CST 2012
     */
    public void setParaId(Long paraId) {
        this.paraId = paraId;
    }
}