package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class VMemDownloadInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_mem_download_info.id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_mem_download_info.app_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    private String appId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_mem_download_info.mem_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    private Long memId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_mem_download_info.download_time
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    private Date downloadTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_mem_download_info
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_mem_download_info.id
     *
     * @return the value of v_mem_download_info.id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_mem_download_info.id
     *
     * @param id the value for v_mem_download_info.id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_mem_download_info.app_id
     *
     * @return the value of v_mem_download_info.app_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_mem_download_info.app_id
     *
     * @param appId the value for v_mem_download_info.app_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_mem_download_info.mem_id
     *
     * @return the value of v_mem_download_info.mem_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public Long getMemId() {
        return memId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_mem_download_info.mem_id
     *
     * @param memId the value for v_mem_download_info.mem_id
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public void setMemId(Long memId) {
        this.memId = memId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_mem_download_info.download_time
     *
     * @return the value of v_mem_download_info.download_time
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public Date getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_mem_download_info.download_time
     *
     * @param downloadTime the value for v_mem_download_info.download_time
     *
     * @ibatorgenerated Tue Nov 13 10:53:16 CST 2012
     */
    public void setDownloadTime(Date downloadTime) {
        this.downloadTime = downloadTime;
    }
}