package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class VMemberInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_no
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.login_id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String loginId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.password
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.name
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.nickname
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_type
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_sex
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memSex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_age
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Date memAge;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_status
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_tel
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memTel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_cell
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memCell;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.storeid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String storeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.create_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.login_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Date loginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.lastupdate_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Date lastupdateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_token
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memToken;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_intro
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memIntro;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.mem_ext
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private String memExt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_member_info.hardwareid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private Long hardwareid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_member_info
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.id
     *
     * @return the value of v_member_info.id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.id
     *
     * @param id the value for v_member_info.id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_no
     *
     * @return the value of v_member_info.mem_no
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemNo() {
        return memNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_no
     *
     * @param memNo the value for v_member_info.mem_no
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemNo(String memNo) {
        this.memNo = memNo == null ? null : memNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.login_id
     *
     * @return the value of v_member_info.login_id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.login_id
     *
     * @param loginId the value for v_member_info.login_id
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.password
     *
     * @return the value of v_member_info.password
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.password
     *
     * @param password the value for v_member_info.password
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.name
     *
     * @return the value of v_member_info.name
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.name
     *
     * @param name the value for v_member_info.name
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.nickname
     *
     * @return the value of v_member_info.nickname
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.nickname
     *
     * @param nickname the value for v_member_info.nickname
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_type
     *
     * @return the value of v_member_info.mem_type
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemType() {
        return memType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_type
     *
     * @param memType the value for v_member_info.mem_type
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemType(String memType) {
        this.memType = memType == null ? null : memType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_sex
     *
     * @return the value of v_member_info.mem_sex
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemSex() {
        return memSex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_sex
     *
     * @param memSex the value for v_member_info.mem_sex
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemSex(String memSex) {
        this.memSex = memSex == null ? null : memSex.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_age
     *
     * @return the value of v_member_info.mem_age
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Date getMemAge() {
        return memAge;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_age
     *
     * @param memAge the value for v_member_info.mem_age
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemAge(Date memAge) {
        this.memAge = memAge;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_status
     *
     * @return the value of v_member_info.mem_status
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemStatus() {
        return memStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_status
     *
     * @param memStatus the value for v_member_info.mem_status
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemStatus(String memStatus) {
        this.memStatus = memStatus == null ? null : memStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_tel
     *
     * @return the value of v_member_info.mem_tel
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemTel() {
        return memTel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_tel
     *
     * @param memTel the value for v_member_info.mem_tel
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemTel(String memTel) {
        this.memTel = memTel == null ? null : memTel.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_cell
     *
     * @return the value of v_member_info.mem_cell
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemCell() {
        return memCell;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_cell
     *
     * @param memCell the value for v_member_info.mem_cell
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemCell(String memCell) {
        this.memCell = memCell == null ? null : memCell.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.storeid
     *
     * @return the value of v_member_info.storeid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.storeid
     *
     * @param storeid the value for v_member_info.storeid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid == null ? null : storeid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.create_time
     *
     * @return the value of v_member_info.create_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.create_time
     *
     * @param createTime the value for v_member_info.create_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.login_time
     *
     * @return the value of v_member_info.login_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.login_time
     *
     * @param loginTime the value for v_member_info.login_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.lastupdate_time
     *
     * @return the value of v_member_info.lastupdate_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Date getLastupdateTime() {
        return lastupdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.lastupdate_time
     *
     * @param lastupdateTime the value for v_member_info.lastupdate_time
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setLastupdateTime(Date lastupdateTime) {
        this.lastupdateTime = lastupdateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_token
     *
     * @return the value of v_member_info.mem_token
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemToken() {
        return memToken;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_token
     *
     * @param memToken the value for v_member_info.mem_token
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemToken(String memToken) {
        this.memToken = memToken == null ? null : memToken.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_intro
     *
     * @return the value of v_member_info.mem_intro
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemIntro() {
        return memIntro;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_intro
     *
     * @param memIntro the value for v_member_info.mem_intro
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemIntro(String memIntro) {
        this.memIntro = memIntro == null ? null : memIntro.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.mem_ext
     *
     * @return the value of v_member_info.mem_ext
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public String getMemExt() {
        return memExt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.mem_ext
     *
     * @param memExt the value for v_member_info.mem_ext
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setMemExt(String memExt) {
        this.memExt = memExt == null ? null : memExt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_member_info.hardwareid
     *
     * @return the value of v_member_info.hardwareid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public Long getHardwareid() {
        return hardwareid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_member_info.hardwareid
     *
     * @param hardwareid the value for v_member_info.hardwareid
     *
     * @ibatorgenerated Mon Nov 19 18:41:31 CST 2012
     */
    public void setHardwareid(Long hardwareid) {
        this.hardwareid = hardwareid;
    }
}