package cn.vstore.appserver.model;

import java.io.Serializable;
import java.util.Date;

public class VOrderPayInfo implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.id
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.merchantsid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String merchantsid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.productid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String productid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.channelid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String channelid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.version
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.merusername
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String merusername;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.meruseremail
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String meruseremail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.privatefield
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String privatefield;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.userid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String userid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.usertp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String usertp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.paytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String paytype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.orderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String orderno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.payorderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String payorderno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.orderstatus
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String orderstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.returnurl
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String returnurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.denomination
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Double denomination;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.cardno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String cardno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.cardpwd
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String cardpwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.cardtype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String cardtype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.cardinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String cardinfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.amount
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Double amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.itemid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String itemid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.reserveinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String reserveinfo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.timestamp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String timestamp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.verifytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String verifytype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.verifystr
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String verifystr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.signstring
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String signstring;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.createdate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Date createdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.paydate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Date paydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.memid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private Long memid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column v_order_pay_info.pkgName
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private String pkgname;
    
    
    private String buytype;

    private String nums;
    
    private String snum;
    
    private String propstype;
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table v_order_pay_info
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.id
     *
     * @return the value of v_order_pay_info.id
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.id
     *
     * @param id the value for v_order_pay_info.id
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.merchantsid
     *
     * @return the value of v_order_pay_info.merchantsid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getMerchantsid() {
        return merchantsid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.merchantsid
     *
     * @param merchantsid the value for v_order_pay_info.merchantsid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setMerchantsid(String merchantsid) {
        this.merchantsid = merchantsid == null ? null : merchantsid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.productid
     *
     * @return the value of v_order_pay_info.productid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.productid
     *
     * @param productid the value for v_order_pay_info.productid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.channelid
     *
     * @return the value of v_order_pay_info.channelid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.channelid
     *
     * @param channelid the value for v_order_pay_info.channelid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.version
     *
     * @return the value of v_order_pay_info.version
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.version
     *
     * @param version the value for v_order_pay_info.version
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.merusername
     *
     * @return the value of v_order_pay_info.merusername
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getMerusername() {
        return merusername;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.merusername
     *
     * @param merusername the value for v_order_pay_info.merusername
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setMerusername(String merusername) {
        this.merusername = merusername == null ? null : merusername.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.meruseremail
     *
     * @return the value of v_order_pay_info.meruseremail
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getMeruseremail() {
        return meruseremail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.meruseremail
     *
     * @param meruseremail the value for v_order_pay_info.meruseremail
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setMeruseremail(String meruseremail) {
        this.meruseremail = meruseremail == null ? null : meruseremail.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.privatefield
     *
     * @return the value of v_order_pay_info.privatefield
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getPrivatefield() {
        return privatefield;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.privatefield
     *
     * @param privatefield the value for v_order_pay_info.privatefield
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setPrivatefield(String privatefield) {
        this.privatefield = privatefield == null ? null : privatefield.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.userid
     *
     * @return the value of v_order_pay_info.userid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.userid
     *
     * @param userid the value for v_order_pay_info.userid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.usertp
     *
     * @return the value of v_order_pay_info.usertp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getUsertp() {
        return usertp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.usertp
     *
     * @param usertp the value for v_order_pay_info.usertp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setUsertp(String usertp) {
        this.usertp = usertp == null ? null : usertp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.paytype
     *
     * @return the value of v_order_pay_info.paytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.paytype
     *
     * @param paytype the value for v_order_pay_info.paytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.orderno
     *
     * @return the value of v_order_pay_info.orderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.orderno
     *
     * @param orderno the value for v_order_pay_info.orderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.payorderno
     *
     * @return the value of v_order_pay_info.payorderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getPayorderno() {
        return payorderno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.payorderno
     *
     * @param payorderno the value for v_order_pay_info.payorderno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setPayorderno(String payorderno) {
        this.payorderno = payorderno == null ? null : payorderno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.orderstatus
     *
     * @return the value of v_order_pay_info.orderstatus
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.orderstatus
     *
     * @param orderstatus the value for v_order_pay_info.orderstatus
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.returnurl
     *
     * @return the value of v_order_pay_info.returnurl
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getReturnurl() {
        return returnurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.returnurl
     *
     * @param returnurl the value for v_order_pay_info.returnurl
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setReturnurl(String returnurl) {
        this.returnurl = returnurl == null ? null : returnurl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.denomination
     *
     * @return the value of v_order_pay_info.denomination
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Double getDenomination() {
        return denomination;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.denomination
     *
     * @param denomination the value for v_order_pay_info.denomination
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setDenomination(Double denomination) {
        this.denomination = denomination;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.cardno
     *
     * @return the value of v_order_pay_info.cardno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.cardno
     *
     * @param cardno the value for v_order_pay_info.cardno
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.cardpwd
     *
     * @return the value of v_order_pay_info.cardpwd
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getCardpwd() {
        return cardpwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.cardpwd
     *
     * @param cardpwd the value for v_order_pay_info.cardpwd
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setCardpwd(String cardpwd) {
        this.cardpwd = cardpwd == null ? null : cardpwd.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.cardtype
     *
     * @return the value of v_order_pay_info.cardtype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.cardtype
     *
     * @param cardtype the value for v_order_pay_info.cardtype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.cardinfo
     *
     * @return the value of v_order_pay_info.cardinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getCardinfo() {
        return cardinfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.cardinfo
     *
     * @param cardinfo the value for v_order_pay_info.cardinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setCardinfo(String cardinfo) {
        this.cardinfo = cardinfo == null ? null : cardinfo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.amount
     *
     * @return the value of v_order_pay_info.amount
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.amount
     *
     * @param amount the value for v_order_pay_info.amount
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.itemid
     *
     * @return the value of v_order_pay_info.itemid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getItemid() {
        return itemid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.itemid
     *
     * @param itemid the value for v_order_pay_info.itemid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setItemid(String itemid) {
        this.itemid = itemid == null ? null : itemid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.reserveinfo
     *
     * @return the value of v_order_pay_info.reserveinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getReserveinfo() {
        return reserveinfo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.reserveinfo
     *
     * @param reserveinfo the value for v_order_pay_info.reserveinfo
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setReserveinfo(String reserveinfo) {
        this.reserveinfo = reserveinfo == null ? null : reserveinfo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.timestamp
     *
     * @return the value of v_order_pay_info.timestamp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.timestamp
     *
     * @param timestamp the value for v_order_pay_info.timestamp
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.verifytype
     *
     * @return the value of v_order_pay_info.verifytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getVerifytype() {
        return verifytype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.verifytype
     *
     * @param verifytype the value for v_order_pay_info.verifytype
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setVerifytype(String verifytype) {
        this.verifytype = verifytype == null ? null : verifytype.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.verifystr
     *
     * @return the value of v_order_pay_info.verifystr
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getVerifystr() {
        return verifystr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.verifystr
     *
     * @param verifystr the value for v_order_pay_info.verifystr
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setVerifystr(String verifystr) {
        this.verifystr = verifystr == null ? null : verifystr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.signstring
     *
     * @return the value of v_order_pay_info.signstring
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getSignstring() {
        return signstring;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.signstring
     *
     * @param signstring the value for v_order_pay_info.signstring
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setSignstring(String signstring) {
        this.signstring = signstring == null ? null : signstring.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.createdate
     *
     * @return the value of v_order_pay_info.createdate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.createdate
     *
     * @param createdate the value for v_order_pay_info.createdate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.paydate
     *
     * @return the value of v_order_pay_info.paydate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.paydate
     *
     * @param paydate the value for v_order_pay_info.paydate
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.memid
     *
     * @return the value of v_order_pay_info.memid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public Long getMemid() {
        return memid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.memid
     *
     * @param memid the value for v_order_pay_info.memid
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setMemid(Long memid) {
        this.memid = memid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column v_order_pay_info.pkgName
     *
     * @return the value of v_order_pay_info.pkgName
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public String getPkgname() {
        return pkgname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column v_order_pay_info.pkgName
     *
     * @param pkgname the value for v_order_pay_info.pkgName
     *
     * @ibatorgenerated Fri Nov 16 14:39:37 CST 2012
     */
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname == null ? null : pkgname.trim();
    }

	public String getBuytype() {
		return buytype;
	}

	public void setBuytype(String buytype) {
		this.buytype = buytype;
	}

	public String getSnum() {
		return snum;
	}

	public void setSnum(String snum) {
		this.snum = snum;
	}

	public String getPropstype() {
		return propstype;
	}

	public void setPropstype(String propstype) {
		this.propstype = propstype;
	}

	public String getNums() {
		return nums;
	}

	public void setNums(String nums) {
		this.nums = nums;
	}
}